spring:
  application:
    name: demoservice

debug:
  false

logging:
  file: ./logs/app.log

---

spring:
  profiles: local

server:
  port: 8080

---

spring:
  profiles: local2

server:
  port: 8081
